os:
- linux
before_install:
- curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
- sudo apt-get install -y nodejs
- npm --version
- node --version
- npx --version
- export ANDROID_HOME=/usr/local/android-sdk
- export PATH=$PATH:$ANDROID_HOME/emulator
- export PATH=$PATH:$ANDROID_HOME/tools
- export PATH=$PATH:$ANDROID_HOME/tools/bin
- export PATH=$PATH:$ANDROID_HOME/platform-tools
- git clone https://github.com/facebook/watchman.git -b v4.9.0 --depth 1
- cd watchman
- "./autogen.sh"
- "./configure"
- make
- sudo make install
- cd ..
install:
- npm install
language: android
jdk:
- oraclejdk8
dist: trusty
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
script:
- cd android && sudo chmod +x gradlew && sudo ./gradlew clean && sudo ./gradlew assembleRelease
- cd ..